### PR TITLE
License and copyright notice shuffle

### PR DESCRIPTION
**Pull request by dwijnand**
Put the license in LICENSE and move the copyright notice to NOTICE.

### CODE REVIEW

**Comment by SethTisue** [comment]
I don't see the point of splitting LICENSE and NOTICE, or of including the full text of the license. It's common for other projects, both inside and outside Lightbend, to do it the way I did it here.  Is there a really good reason to change it?

**Comment by dwijnand** [comment]
1. It'll make GitHub recognise the project as Apache 2.0 licensed
2. It's how the Apache 2.0 license is applied: http://www.apache.org/dev/apply-license.html#new

**Comment by dwijnand** [comment]
Also, btw, I'm happy to make this change for consistency on any other project of Lightbend.

**Comment by SethTisue** [comment]
okay, thanks!

**Comment by SethTisue** [comment]
what do you think about just merging NOTICE into README.md?

**Comment by SethTisue** [comment]
I see that it actually specifies NOTICE, too. TIL

**Comment by adriaanm** [comment]
Thanks @dwijnand!

**Pull request merged**
